name: CI

on:
  push:
    branches: [main, develop]

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gaku10_test

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Start MySQL container manually
        run: |
          docker run -d --rm \
            --name mysql_test \
            -e MYSQL_ROOT_PASSWORD=password \
            -e MYSQL_DATABASE=gaku10_test \
            -p 3306:3306 \
            --health-cmd="mysqladmin ping -ppassword -h 127.0.0.1" \
            --health-interval=5s \
            --health-timeout=10s \
            --health-retries=5 \
            mysql:8.0
          echo "Waiting for MySQL to start..."
          sleep 25

      - name: Setup database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:prepare

      - name: Run RSpec
        run: bundle exec rspec --format documentation
